---
title: "Cluster by Individual Samples"
author: "WYashar & TLusardi"
date: "02/03/2021"
output:
  html_document:
    code_folding: hide
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

### Set-Up

#### Libraries 

```{r setup_libs, include=TRUE}
library(Seurat)
library(data.table)
library(ggplot2)
library(knitr)
library(networkD3)
library(patchwork)
library(dplyr)
library(clustree)
library(circlize)
library(ComplexHeatmap)
library(ggthemes)
library(viridis)
```

#### Varibles

##### Update according to your dataset

```{r setup_variables, include=TRUE}

# Samples to process named by their treatment conditions
samples2process = c("dmso", "quzi", "ory", "combo")

# Name of the single cell project
projectName <- "flt3_aml"

# Date that Seurat object with pre-processed data was generated
importDate <- "2021-02-15"

# Clustering Resolution
clusRes <- 0.7

# Number of dimensions to reduce on
nDims <- 150
```

##### Inherent Variables

```{r setup_inherent_variables, include=TRUE}

# Specify directory paths
directory = list(raw = "./data/raw",
                 rda = "./data/rda")

# Load Seurat objects
exptsList <- readRDS(sprintf("%s/integrated.%s.%s.rds", directory$rda, projectName,importDate))

# Load the integrated object
integratedSO <- exptsList[["integrated"]]
```

### Principal Component Analysis

```{r}
# Run PCA on the integrated object
integratedSO <- RunPCA(integratedSO, npcs = nDims, verbose = FALSE)
```

### Identify UMAP Clustering Variables

``` {r id_umap_vars, include=TRUE}

# Perform linear dimensional reduction (UMAP) 
plotList <- list()

# Create plot that explains variance by Principle Components (PCs) to find the dimensionality
percentExplained <- function( integratedSO ){
   return(cumsum(integratedSO@reductions$pca@stdev^2)/integratedSO@reductions$pca@misc$total.variance)
}

plotPercentExplained <- function( integratedSO , ndims = nDims) {
    data.use <- percentExplained( integratedSO )
    plot <- ggplot(data = data.frame(dims = 1:ndims, var = data.use[1:ndims])) +
            geom_point(mapping = aes_string(x = 'dims', y = 'var')) + labs( y = "% variance explained", x = "PC") +
            ggtitle("Variance Explained by Principle Components") +
            theme_clean()
    return(plot)
}

plotList[["plotPercentExplained"]] <- plotPercentExplained(integratedSO)

# Cluster the cells over a range of resolutions
clustreeObj <- FindNeighbors(object = integratedSO, dims = 1:nDims, verbose = FALSE)
clustreeObj <- clustreeObj %>%
  FindClusters(resolution = seq(0,2,0.1), verbose = FALSE) %>%
  RunUMAP(dims = 1:nDims, verbose = FALSE)

# Add UMAP embedding
embeddings <- Embeddings(integratedSO)
clustreeObj@meta.data$PC_1 <- embeddings[,1]
clustreeObj@meta.data$PC_2 <- embeddings[,2]

# Clustree visualizations to determine best cluster resolution
plotList[["clustree"]] <- clustree(clustreeObj, prefix = "Integrated_snn_res.") 

plotList[["clustreeOverlay"]] <- clustree_overlay(x = clustreeObj[[]],
                 prefix = "Integrated_snn_res.",
                 x_value = "PC_1",
                 y_value = "PC_2") 
```


### UMAP Variable Plots

##### Plot Percent Explained
```{r}
plot(plotList[["plotPercentExplained"]])
```

##### Clustree
```{r}
plotList[["clustree"]]
```

##### Clustree Overlay
```{r}
plotList[["clustreeOverlay"]]
```

### UMAP Clustering 

```{r umap}
plostList <- list()

# Cluster the cells over a range of resolutions
integratedSO <- integratedSO %>%
  FindNeighbors(dims = 1:nDims, verbose = FALSE) %>%
  FindClusters(resolution = clusRes, verbose = FALSE) %>%
  RunUMAP(dims = 1:nDims, verbose = FALSE)

# Plot and save UMAP clusters
Idents(integratedSO) <- integratedSO$seurat_clusters
plotList[["umap"]] <- DimPlot(object = integratedSO, reduction = 'umap', label = TRUE, label.size = 7) 

# Save clustering
exptsList[["integrated"]] <- integratedSO
```

### UMAP Plots 

##### UMAP 

```{r}
plotList[["umap"]]
```

### Save Data

```{r save_data, include=TRUE}
file2save <- sprintf("clustered_all_samples.%s.%s.rds", projectName, Sys.Date())
print(sprintf("Saving clustered data of all samples in %s", file2save))
saveRDS(exptsList, file = paste(directory$rda, file2save, sep = "/"))
```

### Session Information

```{r session_info, include=TRUE}
sessionInfo()
```