# 0 general info ------------------------------------------------------------------------

title: Patient samples treated with control versus drug

authors:
  - first_author
  - second_author
  - pi_1
  - pi_2

# number of cores to utilize
cores: 8

# tracks the beginning of an analysis. This value is preserved across all stages of the analysis.
date: "2021-02-22" # YYYY-MM-DD

# 1 preprocessing -----------------------------------------------------------------------

# list the names of your samples to process.
samples2process:
  - dmso
  - ory

# give the analysis a name.
projectName: "my_project"

# save or don't save seurat object with cell cycle regression
cellCycleRegression: TRUE # TRUE or FALSE

# See QC metrics at these percentiles.
metadataQuants:
  - 0
  - 0.25
  - 0.5
  - 0.75
  - 0.95
  - 1

# filtering criteria
percentMitoFilt: 15
nCountMinFilt: 2000
nCountMaxFilt: 20000

# principle components to calculate for each sample
nPCs: 150

# visualize cell cycle states versus expression level of these cell cycle genes.
cc_genes:
  - NASP
  - USP1
  - TUBB4B
  - HMGB2
  - PCNA
  - TOP2A
  - MCM6
  - MKI67

# 2 integration ------------------------------------------------------------------------

# Set the baseline condition
baseline: "dmso"

# number of principal components to use for FindIntegrationAnchors and IntegrateData.
integration_anchor_PC: 150

# how many neighbors (k) to use when picking anchors
k.anchor: 5

# 3 clustering- -------------------------------------------------------------------------

# 4 cluster annotation ------------------------------------------------------------------
