name: cite-seq ci

on: [push]
- name: snakemake
  uses: snakemake/snakemake-github-action@v1.18.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: SnakeMake Dry run
      uses: snakemake/snakemake-github-action@v1.18.0
      with:
        directory: '.test'
        snakefile: 'Snakefile'
        args: '--cores 1 --use-conda --conda-cleanup-pkgs cache -np'
