name: cite-seq ci

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        environment-file: .github/workflows/snakemake-5.32.2.yaml
        python-version: 3.8
        auto-activate-base: false
    - run: |
      conda info
      conda list
